before_deploy:
  - npm i
  - npm run build

deploy:
  provider: firebase

  token:
    secure: eNAweoLwFhllL5DeO9tq6IM9jPrguinlh+22VLPj+zWLvgcPiaX2Ux1KmYmCH6iAmLHup/2ONPPLS+rNqP5Y/AwMzUExVvgQ0zN0l00NDxpmMXOya96vx2kpP3ZDBbiqXjOqLu9vdNymT84TM3SljpNhn626XsPIx35ULxEYZcyb51YWPUzvn2/cL9Uyn3eOhxxzQ2Fh2x3rSP45kXxLUfhMSnHKbtwOBUAW3Z6qmPRfI03pjH/NNWTHrfTO4XEjSqdrHQqQp0onYYQP44111zm1dVK6rFFVBb6Bt/keE/omnQ9Z86GAzQjD6Tl/5udXXgp6r2pNf4mZpDZdeP8Q75DUeNs38QXcfwwspcSOIlPVdcIAqP1nZxpFlElCk0Un0arPuUN++Y0F+uNXYFY61qZKfJmFaOVAJJSYWlkaaYHRq7rAFWSOXtgMiSizGulF+343W0OD/7PcQWmrUMk46tadin59dzQsoNfqMmAWYTpq0mMVs7M38+WMId8l1447sNWadrDk9BZ7E1cAxgrFue/krQ7bN8KYxZRy/5o84hmlGDZ9CIvW2lyPqFHNK7g1UWtu1SJjGF2KBcotoQ4tnJb4tN9ltotJ7+nCa6xpum8V3PLBk5ZBwT0wlFXgU3hmoj3b3YEqoNBZAp1rO0LfvDVZYQEkfDKIO8BR3I5q3Z8=
